FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o bin/server ./cmd/server

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/bin/server .
EXPOSE 8081
CMD ["./server"]
